esphome:
  name: nanocell
  friendly_name: NanoCell
  libraries:
    - "Wire"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "*************************"

ota:
  password: "*********************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "NanoCell Fallback Hotspot"
    password: "***********"

captive_portal:

# Example configuration entry for NanoCell-C3
i2c:
  sda: 2
  scl: 3
  scan: True
  id: bus_a

sensor:
  - platform: max17043
    id: max17043_id
    i2c_id: bus_a
    battery_voltage:
      name: "Battery Voltage"
    battery_level:
      name: "Battery"